# Generated by Django 4.1.3 on 2022-11-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.URLField(verbose_name='Imagen'),
        ),
    ]
